[general]
import = [
    "~/.config/alacritty/themes/gruvbox_material_medium_dark.toml"
]

[colors.primary]
background = "#141414"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[terminal]
shell = "zsh"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[selection]
save_to_clipboard = false

[window]
opacity = 1

[font]
size = 14

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 1
y = 1

[scrolling]
history = 10000
multiplier = 1
