#!/usr/bin/sh

sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width         2
bspc config window_gap					 6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#autostart
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
