[main]
font=JetBrainsMono Nerd Font:size=15.5
pad=1x1
shell=/usr/bin/zsh

[scrollback]
lines=10000
multiplier=1.0

[cursor]
style=block

[colors-dark]
alpha=0.8

background=000000
foreground=c5c9c5

# normal colors
regular0=090618
regular1=c34043
regular2=76946a
regular3=c0a36e
regular4=7e9cd8
regular5=957fb8
regular6=6a9589
regular7=c8c093

# bright colors
bright0=727169
bright1=e82424
bright2=98bb6c
bright3=e6c384
bright4=7fb4ca
bright5=938aa9
bright6=7aa89f
bright7=dcd7ba

# selection
selection-background=2d4f67
selection-foreground=c8c093
