#!/usr/bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII

bspc config border_width         2
bspc config window_gap					 4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#autostart
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &

# Set monitor resolution and refresh rate
xrandr --output eDP-1 --mode 1920x1080 --rate 144
