#!/usr/bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width         1
bspc config window_gap			 1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#autostart
# picom --config home/.config/picom/picom.conf &
# feh --bg-fill /home/kenjitheman/walls/toxicman.png &
dunst &
polybar &

# Set monitor resolution and refresh rate
xrandr --output eDP-1 --mode 1920x1080 --rate 144
