use_nerdfont = true
audio_cache = true
volnorm = false
default_keybindings = true
notify = false
bitrate = 320
gapless = true
shuffle = false
repeat = "off"
playback_state = "Paused"
library_tabs = ["tracks", "playlists", "albums", "artists"]
hide_display_names = true

statusbar_format = "%artists - %title"

[track_format]
left = "%artists - %title"
center = "%album"
right = "%saved %duration"

# Gruvbox dark [ originally based on base16 by Dawid Kurek (dawikur@gmail.com) ]
[theme]
background = "default"
primary = "#a89984"
secondary = "#928374"
title = "#8ec07c"
playing = "#689d6a"
playing_bg = "#383838"
playing_selected = "#ebdbb2"
highlight = "#d5c4a1"
highlight_bg = "#484848"
error = "#fbf1c7"
error_bg = "#cc241d"
statusbar_progress = "#458588"
statusbar_bg = "#282828"
statusbar = "#98971a"
cmdline = "#d5c4a1"
cmdline_bg = "#383838"
search_match = "#fabd2f"
